--write a SQL query to count number of orders by the combination of each order date and salesperson. Return order date, salesperson id
select * from orders

select  ord_date, salesman_Id, count(*) as totalcount
from orders
group by  ord_date, salesman_Id 

--write a SQL query to count number of salespeople who belongs to a city. Return number of salespeople
select * from salesman

select count(*), city
from salesman
group by city

--write a SQL query to count all the orders generated on '2012-08-17'. Return number of orders.
select * from orders

select count(*) as orders
from orders
where ord_date = '2012-08-17'

--write a SQL query to find the maximum order (purchase) amount generated by each salesperson. 
--Filter the rows for the salesperson ID is in the range 5003 and 5008 (Begin and end values are included.). 
--Return salesperson id and maximum purchase amount
select * from orders

select salesman_Id, max(purch_amt) as 'max purch amt'
from orders
where salesman_Id between 5003 and 5008
group by salesman_Id