----------------DATE FUNCTIONS


--1. GETDATE()​
select GETDATE();

--2. CAST()
select CAST(GETDATE() AS DATE);

--3. CONVERT()
SELECT CONVERT(INT , '01');
SELECT CONVERT(VARCHAR(15), GETDATE(), 101);

--4. DAY
SELECT DAY(GETDATE());

--5. MONTH
SELECT MONTH(GETDATE());

--6. YEAR​
select YEAR(GETDATE());

--7. DATENAME()
SELECT DATENAME(MM,GETDATE());

--8. DATEPART
SELECT DATEPART(MM,GETDATE());

--9​. DATE_ADD
SELECT DATEADD(DD, 3, GETDATE());

--10. DATEDIFFERENCE
SELECT DATEDIFF(YYYY,'20-05-2000','12-01-2022');


------------------------------------STRING FUNCTIONS


--1. UPPERCASE
SELECT UPPER('Nikitha');

--2. LOERCASE
SELECT LOWER('NISA');

--3. CONCAT
SELECT CONCAT('NI', 'SA')

--4. LENGTH
SELECT LEN('2022');

--5. LTRIM
SELECT LTRIM('               NIKITHA');

--6. RTRIM
SELECT LTRIM('               NIKITHA                         ');

--7.REPLACE
SELECT REPLACE('NIKITHA','N','Z');
